name: CI

on: [push]

jobs:
  build-windows:
    runs-on: windows
    steps:
      - uses: actions/checkout@v1
      - name: Windows
        run: CALL gradlew.bat --no-daemon mingwX64Test

  build-mac:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Mac
        run: ./gradlew --no-daemon check -x jsBrowserTest

  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Mac
        run: ./gradlew --no-daemon check -x jsBrowserTest
