name: CI

on: [push]

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Windows
        run: CALL gradlew.bat --no-daemon mingwX64Test
        shell: cmd

  build-mac:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Mac
        run: ./gradlew --no-daemon check -x jsBrowserTest

  build-linux:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Linux
        run: ./gradlew --no-daemon check -x jsBrowserTest
